### ISSUE TITLE
Doesn't work in GUI apps

### ISSUE THREAD

**Issue by pgol** [bahmutov/pre-git#85]
```env: node: No such file or directory```

I guess it's related to loading different environment by GUI app that is loaded in my shell.  But is there any way to fix it in this module?

**Comment by bahmutov** [comment]
the hooks themselves are written in Node, so they cannot work if there is no Node. Is it possible to have node in the path?

**Comment by pgol** [comment]
I use zsh and nvm so when I start SourceTree from finder it does't see my environment. My fix is to just open GUI app from terminal with for example:

```open -a SourceTree```

and then it works, I don't use GUI apps for git that often. Thank you for responding.

**Comment by pulkitsinghal** [comment]
Want to throw some buzz words in here to help people find your solution:
```
env: node: No such file or directory
```

Fix was as @pgol pointed out. For a few minor caveats see [this](https://answers.atlassian.com/questions/140339/answers/32030983).

1. `stree` is the only thing you need to type if you are already in the directory of interest and sourcetree command line tools are already installed
2. you MUST close all windows and quit sourcetree completely ... only closing the windows is not enough because that means that previous sourcetree process without the PATH is still running!
